### ISSUE TITLE
add health check code

### ISSUE THREAD

**Issue by saramsey** [RTXteam/PloverDB#1]
Need a health check code endpoint that will return status code 200 if the service is up.

**Comment by saramsey** [comment]
(per communication from Ke Wang at NCATS IT)

**Comment by saramsey** [comment]
I am working this issue at the moment....

**Comment by saramsey** [comment]
OK, in my docker container, the new healthcheck endpoint works. Inside the container, running this command:
```
curl -I -l http://localhost/healthcheck/
```
when the PloverDB is already running, produces this output:
<img width="518" alt="Screen Shot 2021-06-08 at 11 49 53 AM" src="https://user-images.githubusercontent.com/5562107/121240870-a7e97a80-c84f-11eb-9433-b05ec56da247.png">

Now let's stop PloverDB:
```
kill -TERM 10
```
Running that same curl command when PloverDB is not already running, produces this output:
<img width="574" alt="Screen Shot 2021-06-08 at 11 48 39 AM" src="https://user-images.githubusercontent.com/5562107/121240731-84263480-c84f-11eb-8b26-e5ece67867e3.png">

**Comment by saramsey** [comment]
Needed to add a `kg2c-test.json` file to use for testing, or else this test would take forever (and I don't even have enough memory to load the real `kg2c.json` file)

**Comment by saramsey** [comment]
Also added logging to `uwsgi.ini` for debugging purposes

**Comment by saramsey** [comment]
OK, commits 710c747 07c3dee and 47a311d should take care of it (I hope).

**Comment by amykglen** [comment]
thanks, Steve! 

re: the test file - fyi, there was a mechanism to load a test file - you just need to set `"is_test"` to `true` in `kg_config.json` (which is located in the repo at `PloverDB/app/kg_config.json`) - then if you have `  "download_latest_kg2c": true` in the config file, a small test version of the KG will be downloaded from S3 and used. or if you wanted to use your own test file, you just locally put it into your clone of the repo at `PloverDB/app` and adjust these lines of `kg_config.json` like so:
```
  "download_latest_kg2c": false,
  "local_kg_file_name": "my_test_kg.json",
```
though perhaps it's nice to have a test KG actually checked into the repo!

**Comment by amykglen** [comment]
closing since all seems to work well here!
