### ISSUE TITLE
load kg2c_lite_X.X.X.json.gz from a different source than translator-lfs-artifacts

### ISSUE THREAD

**Issue by saramsey** [RTXteam/PloverDB#19]
Currently, the [instructions for deploying PloverDB with a new version of KG2c](https://github.com/RTXteam/PloverDB/wiki/Deployment-how-tos#to-build-plover-from-a-new-kg2-version) specify to upload the new version of KG2c (specifically, the "lite" serialization with fewer properties), in JSON format, i.e., `kg2c_lite_X.X.X.json.gz`, to [github:ncats/translator-lfs-artifacts](https://github.com/ncats/translator-lfs-artifacts/) so that PloverDB can load the file from there at the time the service is built on Jenkins. The problem is that neither I nor @sundareswarpullela have permissions to commit to the `main` branch on the `translator-lfs-artifacts` GitHub project area. With Noel Southall having moved on to industry, it is unclear who can grant those permissions (Mark W. reportedly does not have permissions to do it). A request has been sent to ITRB but in the meantime, we need a workaround. Longer-term, it seems (in hindsight) not optimal to have our deployment gate on staging a data artifact in a project area that we don't administratively control, though admittedly, there is a real benefit (which we have discussed at length) to staging the KG2c lite JSON dump in a project area maintained by NCATS. Any alternative hosting mechanism is going to require code changes to PloverDB, which I propose to commit under this issue. In a sense, [RTXteam/RTX issue 2056](https://github.com/RTXteam/RTX/issues/2056) is blocking on this issue.

**Comment by saramsey** [comment]
Per suggestion from @sundareswarpullela , I will do this work in the [`main` branch](https://github.com/RTXteam/PloverDB/tree/main).

**Comment by sundareswarpullela** [comment]
@saramsey the file can be found at `RTX/code/kg2c/kg2c_lite.json.gz` on `buildkg2c.rtx.ai` it can be renamed to `kg2c_2.8.3.json.gz`

**Comment by saramsey** [comment]
Sundar, that file is only 2.2 MiB.  That seems small. Any ideas why?

**Comment by saramsey** [comment]
I think commit 343942b should do it, but I can't fully test it until I have a complete `kg2c_2.8.3.json.gz` file with which to test it. The aforementioned file (retrieved from `buildkg2c.rtx.ai` this afternoon) is too small; something seems wrong with it, and consistent with that, when I try to run `build_indexes.py`, I get a `KeyError`.
