### ISSUE TITLE
test 21 should be returning two edges

### ISSUE THREAD

**Issue by saramsey** [RTXteam/PloverDB#22]
@amykglen wrote (via Slack DM):  _my edits shown in square brackets_

> as a separate issue - [for PloverDB unit test `test_21`], I would think the `upregulated` edge should also be returned ... (in addition to the `increased` edge), since `upregulated` is a descendant of `increased`. I'm guessing this is a bug with Plover that's probably been present for a while. the upregulated edge should be indexed under 'increased' in this section: https://github.com/RTXteam/PloverDB/blob/30693542e4428b8d83d13d8d39b6c0facff0d273/app/app/plover.py#L329-L338
> so I'm not sure why it isn't returned (I tested by removing the aspect qualifier from test_21).

**Comment by saramsey** [comment]
Here is the link to `test_2`:
https://github.com/RTXteam/PloverDB/blob/30693542e4428b8d83d13d8d39b6c0facff0d273/test/test.py#L631

**Comment by amykglen** [comment]
was an issue with BiolinkHelper - fixed here: https://github.com/RTXteam/RTX/commit/30896deb72c46c7a686543f96f4ae786046f052b

thanks!
